name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - aom=3.6.0=h6a678d5_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boltons=24.1.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cffi=1.17.1=py312h1fdaa30_1
  - conda=24.11.3=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.7.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312h06a4308_0
  - conda-package-streaming=0.11.0=py312h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fmt=9.1.0=hdb19cb5_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h55d465d_3
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.4.2=py312h06a4308_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hf296adc_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.83.1=h38339ff_5
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarchive=3.7.7=hfab0078_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=28_h59b9bed_openblas
  - libcblas=3.9.0=28_he106b2a_openblas
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libmamba=1.5.11=hfe524e5_1
  - libmambapy=1.5.11=py312haf1ee3a_1
  - libmediainfo=24.12=h1935945_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopenvino=2024.1.0=h2da1b83_7
  - libopenvino-auto-batch-plugin=2024.1.0=hb045406_7
  - libopenvino-auto-plugin=2024.1.0=hb045406_7
  - libopenvino-hetero-plugin=2024.1.0=h5c03a75_7
  - libopenvino-intel-cpu-plugin=2024.1.0=h2da1b83_7
  - libopenvino-intel-gpu-plugin=2024.1.0=h2da1b83_7
  - libopenvino-intel-npu-plugin=2024.1.0=he02047a_7
  - libopenvino-ir-frontend=2024.1.0=h5c03a75_7
  - libopenvino-onnx-frontend=2024.1.0=h07e8aee_7
  - libopenvino-paddle-frontend=2024.1.0=h07e8aee_7
  - libopenvino-pytorch-frontend=2024.1.0=he02047a_7
  - libopenvino-tensorflow-frontend=2024.1.0=h39126c6_7
  - libopenvino-tensorflow-lite-frontend=2024.1.0=he02047a_7
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsolv=0.7.30=he621ea3_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hfdd30dd_0
  - libzen=0.4.41=h5888daf_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - menuinst=2.1.2=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - numpy-base=2.0.1=py312h0da6c21_1
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.16=h5eee18b_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.2=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pluggy=1.5.0=py312h06a4308_0
  - proglog=0.1.10=pyhaa61c55_0
  - pugixml=1.14=h59595ed_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_2
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - python_abi=3.12=5_cp312
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_0
  - ruamel.yaml=0.18.6=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py312h5eee18b_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.45.3=h5eee18b_0
  - svt-av1=2.1.0=hac33072_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=h6a678d5_2
  - tinyxml2=10.0.0=h3f2d84a_2
  - tk=8.6.14=h39e8969_0
  - tqdm=4.67.1=py312he106c6f_0
  - truststore=0.10.0=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py312h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.2.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.46.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - apex==0.1
      - attrs==24.3.0
      - audioread==3.0.1
      - av==14.1.0
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.45.0
      - blinker==1.9.0
      - boto3==1.35.82
      - botocore==1.35.82
      - certifi==2024.12.14
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colossalai==0.4.6
      - contexttimer==0.3.3
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - datasets==3.2.0
      - decorator==4.4.2
      - decord==0.6.0
      - deprecated==1.2.15
      - diffusers==0.32.0.dev0
      - dill==0.3.8
      - distlib==0.3.9
      - distvae==0.0.0b4
      - docstring-parser==0.16
      - einops==0.8.0
      - fabric==3.2.2
      - fastapi==0.115.6
      - filelock==3.16.1
      - flash-attn==2.7.4.post1
      - flask==3.1.0
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - galore-torch==1.0
      - google==3.0.0
      - h11==0.14.0
      - hf-transfer==0.1.8
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - identify==2.6.3
      - idna==3.10
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - inquirerpy==0.3.4
      - invoke==2.2.0
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jax==0.4.35
      - jaxlib==0.4.35
      - jinja2==3.1.4
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - llvmlite==0.44.0
      - loguru==0.7.3
      - lumaai==1.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - mmengine==0.10.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nodeenv==1.9.1
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - openai==1.57.4
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optimum-quanto==0.2.6
      - pandas==2.2.3
      - parameterized==0.9.0
      - paramiko==3.5.0
      - peft==0.14.0
      - pfzy==0.3.4
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plumbum==1.9.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - pre-commit==4.0.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.1
      - psutil==6.1.0
      - pyarrow==18.1.0
      - pyav==12.3.0
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pynacl==1.5.0
      - pyparsing==3.2.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - pytorchvideo==0.1.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzipper==0.3.6
      - qwen-vl-utils==0.0.8
      - ray==2.40.0
      - referencing==0.35.1
      - regex==2024.11.6
      - repe==0.1.4
      - rich==13.9.4
      - rotary-embedding-torch==0.8.6
      - rpds-py==0.22.3
      - rpyc==6.0.0
      - s3transfer==0.10.4
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - setuptools==75.6.0
      - shtab==1.7.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - timm==1.0.12
      - tokenizers==0.21.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.6.0
      - torchvision==0.20.1+cu121
      - transformers==4.50.0.dev0
      - triton==3.1.0
      - trl==0.11.3
      - typing-extensions==4.12.2
      - tyro==0.8.11
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.29.0
      - virtualenv==20.28.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - xformers==0.0.27.post2
      - xfuser==0.4.0
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
      - yunchang==0.5.0
      - zipp==3.21.0
prefix: /home/yujinpotter/miniconda
