name: dlib_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cmake=3.26.4=h96355d8_0
  - cuda-cudart=12.4.127=0
  - cuda-cudart_linux-64=12.6.68=h3f2d84a_0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=h7480c83_3
  - cudnn=9.2.1.18=hbc370b7_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=6_ha36c22a_netlib
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=h5888daf_0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=6_ha36c22a_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.2=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.68=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - nccl=2.22.3.1=hbc370b7_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=5_cp310
  - pytorch=2.4.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - rhash=1.4.3=hdbd6064_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.32.3=hcee41ef_1
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.1=py310_cu124
  - torchtriton=3.0.0=py310
  - torchvision=0.19.1=py310_cu124
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - boto3==1.35.34
      - botocore==1.35.34
      - dlib==19.24.9
      - jmespath==1.0.1
      - pandas==2.2.3
      - pytz==2024.2
      - s3transfer==0.10.2
      - tqdm==4.67.1
      - tzdata==2024.2
prefix: /home/yujinpotter/miniconda/envs/dlib_env
