name: mmdt-adv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - av==14.1.0
      - backoff==2.2.1
      - bert-score==0.3.13
      - blinker==1.9.0
      - blis==1.2.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.11
      - decord==0.6.0
      - diffusers==0.33.0.dev0
      - diskcache==5.6.3
      - distro==1.9.0
      - easydict==1.13
      - einops==0.8.1
      - en-core-web-sm==3.8.0
      - exceptiongroup==1.2.2
      - flask==3.1.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - inflect==7.5.0
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - langfuse==2.59.3
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - networkx==3.4.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.63.2
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.5.0
      - pillow==11.1.0
      - preshed==3.0.9
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - thinc==8.3.4
      - timm==1.0.14
      - tokenizers==0.21.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.2.0
      - typeguard==4.4.2
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0
prefix: /ib-scratch/chenguang04/scratch/kyle/.conda/envs/mmdt-adv
